# networks 를 host로 설정하고 각 컨테이너 entrypoint.sh 를 동작 후 redis-cluster-entry에 커멘드 실행하면 동작은 됨
version: "3.8"
services:
  app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    networks:
      - my-networks
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

  redis-node1:
    image: aysel0413/redis:0.1
    container_name: redis-node1
    networks:
      - my-networks
    ports:
      - 7000:7000
    volumes: # 작성한 설정 파일을 볼륨을 통해 컨테이너에 공유
      - ./conf1/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node2:
    image: aysel0413/redis:0.1
    container_name: redis-node2
    networks:
      - my-networks
    ports:
      - 7001:7001
    volumes:
      - ./conf2/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node3:
    image: aysel0413/redis:0.1
    container_name: redis-node3
    networks:
      - my-networks
    ports:
      - 7002:7002
    volumes:
      - ./conf3/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node4:
    image: aysel0413/redis:0.1
    container_name: redis-node4
    networks:
      - my-networks
    ports:
      - 7003:7003
    volumes:
      - ./conf4/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node5:
    image: aysel0413/redis:0.1
    container_name: redis-node5
    networks:
      - my-networks
    ports:
      - 7004:7004
    volumes:
      - ./conf5/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node6:
    image: aysel0413/redis:0.1
    container_name: redis-node6
    networks:
      - my-networks
    ports:
      - 7005:7005
    volumes:
      - ./conf6/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster:
    image: aysel0413/redis:0.1
    container_name: redis-cluster
    networks:
      - my-networks
    ports:
      - 6379:6379
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

networks:
  my-networks:
    driver: bridge