# networks 를 host로 설정하고 각 컨테이너 entrypoint.sh 를 동작 후 redis-cluster-entry에 커멘드 실행하면 동작은 됨
version: "3.8"
services:
  redis-node1:
    image: aysel0413/redis:0.1
    container_name: redis-node1
    networks:
      my-networks:
        ipv4_address: 172.28.0.3
    ports:
      - 7000:7000
      - 17000:17000
    volumes: # 작성한 설정 파일을 볼륨을 통해 컨테이너에 공유
      - ./conf1/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node2:
    image: aysel0413/redis:0.1
    container_name: redis-node2
    networks:
      my-networks:
        ipv4_address: 172.28.0.4
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - ./conf2/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node3:
    image: aysel0413/redis:0.1
    container_name: redis-node3
    networks:
      my-networks:
        ipv4_address: 172.28.0.5
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - ./conf3/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node4:
    image: aysel0413/redis:0.1
    container_name: redis-node4
    networks:
      my-networks:
        ipv4_address: 172.28.0.6
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - ./conf4/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node5:
    image: aysel0413/redis:0.1
    container_name: redis-node5
    networks:
      my-networks:
        ipv4_address: 172.28.0.7
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - ./conf5/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node6:
    image: aysel0413/redis:0.1
    container_name: redis-node6
    networks:
      my-networks:
        ipv4_address: 172.28.0.8
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - ./conf6/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster:
    image: aysel0413/redis:0.1
    container_name: redis-cluster
    networks:
      my-networks:
        ipv4_address: 172.28.0.9
    command: redis-cli --cluster create redis-node1:7000 redis-node2:7001 redis-node3:7002 redis-node4:7003 redis-node5:7004 redis-node6:7005 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

networks:
  my-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16